-- MySQL Script generated by MySQL Workbench
-- Mon Jan 13 03:36:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CCS_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CCS_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CCS_DB` DEFAULT CHARACTER SET utf8 ;
USE `CCS_DB` ;

-- -----------------------------------------------------
-- Table `CCS_DB`.`ChatLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CCS_DB`.`ChatLog` (
  `id` INT NOT NULL,
  `room` VARCHAR(45) NULL,
  `user` VARCHAR(45) NULL,
  `message` LONGTEXT NULL,
  `senttime` REAL NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CCS_DB`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CCS_DB`.`Rooms` (
  `id` INT NOT NULL,
  `checkc` LONGTEXT NULL,
  `adminpw` LONGTEXT NULL,
  `lastjoin` REAL NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CCS_DB`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CCS_DB`.`Users` (
  `id` INT NOT NULL,
  `checkc` LONGTEXT NULL,
  `adminpw` LONGTEXT NULL,
  `lastlogin` REAL NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
